# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/statistics_tests',
                'doc_host': 'https://reutkeller.github.io',
                'git_url': 'https://github.com/reutkeller/statistics_tests',
                'lib_path': 'statistics_tests'},
  'syms': { 'statistics_tests.core': {'statistics_tests.core.foo': ('core.html#foo', 'statistics_tests/core.py')},
            'statistics_tests.sig_test': {}}}
