# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils/CONSTANTS.ipynb.

# %% auto 0
__all__ = ['user_defined_number', 'str_id', 'shapiro_group_code_str', 'shapiro_statistic_str', 'shapiro_p_value_str',
           'group_code_str', 'p_value_str', 'sig_test_name_col_name', 'anova_name_str', 'kruskal_name_str',
           'p_value_border']

# %% ../nbs/utils/CONSTANTS.ipynb 3
user_defined_number = 50

str_id = 'A'


#shapiro table

shapiro_group_code_str = 'group_code'
shapiro_statistic_str='shapiro_statistic'
shapiro_p_value_str ='shapiro_p_value'

#anova / significant differnce test 
group_code_str = 'group_code'
p_value_str= 'p_value'

sig_test_name_col_name = 'test_name'


anova_name_str='one_way_anova'
kruskal_name_str= 'kruskal'

p_value_border = 0.05

