# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/statistics_tests/significant_test.ipynb.

# %% auto 0
__all__ = ['data', 'df', 'anova_test']

# %% ../nbs/statistics_tests/significant_test.ipynb 3
import pandas as pd
import numpy as np
# import statsmodels.api as sm
# import scipy.stats as stats
# from statsmodels.formula.api import ols

import matplotlib.pyplot as plt
import scipy.stats as stats

# import seaborn as sns


# import scikit_posthocs as sp
# import pandas as pd
# import numpy as np
# from io import StringIO

# from statistics_tests import const_vals as const

# %% ../nbs/statistics_tests/significant_test.ipynb 7
data = {
    'id': [str_id + str(i) for i in range(1, user_defined_number + 1)],
    'value': np.random.rand(user_defined_number).tolist(),
    'group': np.random.randint(1, 7, size=user_defined_number).tolist()
}
df=pd.DataFrame(data)
df.head(5)

# %% ../nbs/statistics_tests/significant_test.ipynb 10
def anova_test(
    df : pd.DataFrame , # DataFrame containing the observations and a column specifying the group to which each observation belongs.
    group_col_name : str, # the column name which contain the group code 
    values_col_name : str , # the coulmn name of the column that contains the values of each observation
    ):
  
  values = df[group_col_name].unique().tolist()

  shapiros={'value' : [], 'shapiro_statistic': [] , 'shapiro_p_value':[]}
  for value in values:
        tmp = df[df[group_col_name] == value]
        shapiro_test = stats.shapiro(tmp[tmp[group_col_name] == value][values_col_name])

        shapiros['value'].append(value)
        shapiros['shapiro_statistic'].append(shapiro_test[0])
        shapiros['shapiro_p_value'].append(shapiro_test[1])


  shapiros_df=pd.DataFrame(shapiros)
  
  
  return shapiros_df
        
  
